version: '2'

services:
    nginx_todo:
      build:
        context: ./nginx
      volumes:
        - ${APP_CODE_TODO_PATH_HOST}:${APP_CODE_TODO_PATH_CONTAINER}
        - ${NGINX_TODO_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_TODO_SITE_PATH}:/etc/nginx/sites-available/todo.conf
        - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      ports:
        - "${NGINX_TODO_HOST_HTTP_PORT}:80"
        - "${NGINX_TODO_HOST_HTTPS_PORT}:443"
#      depends_on:
#        - todo
#      links:
#        - todo 
      networks:
        - frontend

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  db:
    driver: ${VOLUMES_DRIVER}   
  redis:
    driver: ${VOLUMES_DRIVER} 
  nginx_todo:
    driver: ${VOLUMES_DRIVER}
